/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, KasMasuk, KasKeluar, InventarisLogistik, RapatPengajuan, Kategori, Postingan } from './types';

export const initialUsers: User[] = [
  {
    email: 'bukukassekolah@gmail.com',
    nama: 'Owner (bukukassekolah@gmail.com)',
    role: 'Super Admin',
    status: 'Aktif',
    tanggalDaftar: '2026-07-04',
  },
  {
    email: 'superadmin@masjid.org',
    nama: 'H. Syarifuddin',
    role: 'Super Admin',
    status: 'Aktif',
    tanggalDaftar: '2026-01-01',
  },
  {
    email: 'admin@masjid.org',
    nama: 'Muhammad Al-Fatih',
    role: 'Admin',
    status: 'Aktif',
    tanggalDaftar: '2026-01-01',
  },
  {
    email: 'bendahara1@masjid.org',
    nama: 'Herman Wijaya',
    role: 'Bendahara 1',
    status: 'Aktif',
    tanggalDaftar: '2026-01-02',
  },
  {
    email: 'bendahara2@masjid.org',
    nama: 'Ahmad Subarjo',
    role: 'Bendahara 2',
    status: 'Aktif',
    tanggalDaftar: '2026-01-02',
  },
  {
    email: 'sekretaris@masjid.org',
    nama: 'Budi Raharjo',
    role: 'Sekretaris',
    status: 'Aktif',
    tanggalDaftar: '2026-01-03',
  },
  {
    email: 'ketua@masjid.org',
    nama: 'Drs. KH. Ahmad Fauzi',
    role: 'Ketua DKM',
    status: 'Aktif',
    tanggalDaftar: '2026-01-01',
  },
];

export const initialKasMasuk: KasMasuk[] = [
  {
    id: 'M-001',
    tanggal: '2026-06-15',
    kategori: 'Infaq Jumat',
    keterangan: 'Infak kotak amal salat Jumat perdana Juni',
    nominal: 4500000,
    buktiUrl: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=400&auto=format&fit=crop&q=60',
    inputOleh: 'bendahara1@masjid.org',
    timestamp: '2026-06-15T13:00:00Z',
  },
  {
    id: 'M-002',
    tanggal: '2026-06-18',
    kategori: 'Zakat Fitrah',
    keterangan: 'Penerimaan zakat fitrah keluarga Bapak Junaedi (5 jiwa)',
    nominal: 225000,
    buktiUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&auto=format&fit=crop&q=60',
    inputOleh: 'bendahara1@masjid.org',
    timestamp: '2026-06-18T10:00:00Z',
  },
  {
    id: 'M-003',
    tanggal: '2026-06-20',
    kategori: 'Infaq Terikat',
    keterangan: 'Donasi hamba Allah untuk pembangunan menara masjid',
    nominal: 5000000,
    buktiUrl: '',
    inputOleh: 'bendahara1@masjid.org',
    timestamp: '2026-06-20T08:30:00Z',
  },
  {
    id: 'M-004',
    tanggal: '2026-06-25',
    kategori: 'Infaq Jumat',
    keterangan: 'Infak kotak amal Jumat kedua Juni',
    nominal: 3850000,
    buktiUrl: '',
    inputOleh: 'superadmin@masjid.org',
    timestamp: '2026-06-25T13:15:00Z',
  },
  {
    id: 'M-005',
    tanggal: '2026-06-28',
    kategori: 'Infaq Terikat',
    keterangan: 'Bantuan dari Yayasan Madani Indonesia',
    nominal: 10000000,
    buktiUrl: '',
    inputOleh: 'bendahara1@masjid.org',
    timestamp: '2026-06-28T16:00:00Z',
  },
];

export const initialKasKeluar: KasKeluar[] = [
  {
    id: 'K-001',
    tanggal: '2026-06-16',
    kategori: 'Perawatan',
    keterangan: 'Pembelian sabun pel, sapu, pembersih kaca, dan pengharum ruangan',
    nominal: 350000,
    buktiUrl: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=400&auto=format&fit=crop&q=60',
    inputOleh: 'bendahara2@masjid.org',
    timestamp: '2026-06-16T14:30:00Z',
  },
  {
    id: 'K-002',
    tanggal: '2026-06-19',
    kategori: 'Konsumsi',
    keterangan: 'Konsumsi rapat koordinasi DKM mingguan',
    nominal: 300000,
    buktiUrl: '',
    inputOleh: 'bendahara2@masjid.org',
    timestamp: '2026-06-19T09:00:00Z',
  },
  {
    id: 'K-003',
    tanggal: '2026-06-22',
    kategori: 'Honor Imam',
    keterangan: 'Mukafah bulanan untuk imam rawatib utama',
    nominal: 3000000,
    buktiUrl: '',
    inputOleh: 'bendahara2@masjid.org',
    timestamp: '2026-06-22T17:00:00Z',
  },
  {
    id: 'K-004',
    tanggal: '2026-06-26',
    kategori: 'Konsumsi',
    keterangan: 'Konsumsi pengajian bulanan jemaah ibu-ibu',
    nominal: 1000000,
    buktiUrl: '',
    inputOleh: 'superadmin@masjid.org',
    timestamp: '2026-06-26T11:00:00Z',
  },
  {
    id: 'K-005',
    tanggal: '2026-06-29',
    kategori: 'Listrik',
    keterangan: 'Pembayaran tagihan listrik token utama masjid',
    nominal: 1850000,
    buktiUrl: '',
    inputOleh: 'bendahara2@masjid.org',
    timestamp: '2026-06-29T10:15:00Z',
  },
];

export const initialInventaris: InventarisLogistik[] = [
  {
    id: 'INV-001',
    tanggal: '2026-05-10',
    namaBarang: 'Karpet Sajadah Turkiye',
    jenisLogistik: 'Masuk',
    kategori: 'Perlengkapan Ibadah',
    volume: 6,
    satuan: 'Roll',
    sumberPeruntukan: 'Wakaf H. Ramli',
    keterangan: 'Karpet tebal kualitas premium warna hijau terpasang di saf utama',
    inputOleh: 'sekretaris@masjid.org',
    timestamp: '2026-05-10T11:00:00Z',
  },
  {
    id: 'INV-002',
    tanggal: '2026-05-15',
    namaBarang: 'Wireless Microphone Shure',
    jenisLogistik: 'Masuk',
    kategori: 'Elektronik & Sound',
    volume: 2,
    satuan: 'Unit',
    sumberPeruntukan: 'Kas Masjid (Beli)',
    keterangan: 'Mic handheld nirkabel tipe UHF untuk imam & penceramah',
    inputOleh: 'sekretaris@masjid.org',
    timestamp: '2026-05-15T15:30:00Z',
  },
  {
    id: 'INV-003',
    tanggal: '2026-06-10',
    namaBarang: 'Al-Qur\'an Terjemahan Rasm Usmani',
    jenisLogistik: 'Masuk',
    kategori: 'Kitab Suci',
    volume: 50,
    satuan: 'Buku',
    sumberPeruntukan: 'Donasi Kedutaan Arab Saudi',
    keterangan: 'Ditempatkan di lemari utama untuk tadarus jemaah',
    inputOleh: 'sekretaris@masjid.org',
    timestamp: '2026-06-10T09:00:00Z',
  },
  {
    id: 'INV-004',
    tanggal: '2026-06-24',
    namaBarang: 'Masker Medis 3-Ply',
    jenisLogistik: 'Keluar',
    kategori: 'Kesehatan / Higienitas',
    volume: 5,
    satuan: 'Box',
    sumberPeruntukan: 'Dibagikan gratis ke jemaah Salat Jumat',
    keterangan: 'Penyaluran rutin untuk menjaga prokes jemaah',
    inputOleh: 'sekretaris@masjid.org',
    timestamp: '2026-06-24T12:00:00Z',
  },
];

export const initialRapatPengajuan: RapatPengajuan[] = [
  {
    id: 'RAP-001',
    tanggal: '2026-06-10',
    judul: 'Pengadaan Mesin Pembersih Vakum (Vacuum Cleaner)',
    deskripsi: 'Mesin penyedot debu lama rusak berat. Dibutuhkan tipe industri heavy duty merk Karcher untuk membersihkan karpet utama setiap hari.',
    estimasiBiaya: 2800000,
    status: 'Disetujui',
    diajukanOleh: 'sekretaris@masjid.org',
    disetujuiOleh: 'ketua@masjid.org',
    timestamp: '2026-06-10T21:00:00Z',
  },
  {
    id: 'RAP-002',
    tanggal: '2026-06-20',
    judul: 'Renovasi Tempat Wudu Wanita (Pintu & Kran Bocor)',
    deskripsi: 'Banyak kran air yang longgar dan bocor. Diperlukan penggantian 8 buah kran kuningan tebal dan perbaikan engsel pintu bilik wudu wanita.',
    estimasiBiaya: 1500000,
    status: 'Diajukan',
    diajukanOleh: 'sekretaris@masjid.org',
    timestamp: '2026-06-20T19:30:00Z',
  },
  {
    id: 'RAP-003',
    tanggal: '2026-06-29',
    judul: 'Santunan Akbar Anak Yatim Menyambut Muharram',
    deskripsi: 'Pengajuan anggaran sosial santunan tunai & bingkisan sekolah untuk 50 anak yatim piatu di lingkungan kelurahan setempat.',
    estimasiBiaya: 15000000,
    status: 'Draft',
    diajukanOleh: 'sekretaris@masjid.org',
    timestamp: '2026-06-29T14:00:00Z',
  },
];

export const initialKategori: Kategori[] = [
  // Pemasukan: baris 1-8
  { namaKategori: 'Infaq Jumat', jenis: 'Masuk' },
  { namaKategori: 'Infaq Umum', jenis: 'Masuk' },
  { namaKategori: 'Infaq Terikat', jenis: 'Masuk' },
  { namaKategori: 'Donasi QRIS', jenis: 'Masuk' },
  { namaKategori: 'Kotak Amal', jenis: 'Masuk' },
  { namaKategori: 'Zakat Fitrah', jenis: 'Masuk' },
  { namaKategori: 'Zakat Mal', jenis: 'Masuk' },
  
  // Pengeluaran: baris 9-14
  { namaKategori: 'Honor Imam', jenis: 'Keluar' },
  { namaKategori: 'Honor Penceramah', jenis: 'Keluar' },
  { namaKategori: 'Honor Marbot', jenis: 'Keluar' },
  { namaKategori: 'Konsumsi', jenis: 'Keluar' },
  { namaKategori: 'Listrik', jenis: 'Keluar' },
  { namaKategori: 'Perawatan', jenis: 'Keluar' },
];

export const initialPostingan: Postingan[] = [
  {
    id: 'PST-001',
    tanggal: '2026-07-01',
    judul: 'Kegiatan Sosial Khitanan Massal Gembira 1447 H',
    konten: 'Assalamu\'alaikum Wr. Wb.\n\nDalam rangka menyambut tahun baru Islam, DKM Al-Amanah bekerja sama dengan tim medis setempat akan mengadakan acara "Khitanan Massal Gembira Gratis" bagi 50 anak yatim dan dhuafa di lingkungan sekitar masjid.\n\nKami membuka kesempatan emas bagi segenap jamaah sekalian untuk berkontribusi mendonasikan sebagian rezeki terbaiknya guna menyukseskan program kebaikan ini. Estimasi biaya per anak adalah Rp 350.000 (mencakup biaya medis, bingkisan baju koko, sarung, peci, uang saku khitan, dan konsumsi).\n\nMari bergotong-royong demi mengukir senyum di wajah mereka. Jazakumullah Khairan Katsiran.',
    tipe: 'Ajakan Donasi',
    tautanDonasi: true,
    targetDonasi: 17500000,
    terkumpulDonasi: 8500000,
    gambarUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=800&auto=format&fit=crop',
    dibuatOleh: 'sekretaris@masjid.org',
    namaPembuat: 'Budi Raharjo',
    timestamp: '2026-07-01T08:00:00Z'
  },
  {
    id: 'PST-002',
    tanggal: '2026-07-04',
    judul: 'Penerimaan Penyaluran Wakaf Mushaf Al-Qur\'an Baru',
    konten: 'Alhamdulillah, telah diterima sebanyak 50 mushaf Al-Qur\'an terjemahan baru bantuan dari Kedutaan Besar Arab Saudi yang saat ini telah ditempatkan di rak buku ruang utama masjid. Mushaf ini terbuka lebar untuk digunakan bertadarus oleh jamaah sekalian setelah salat rawatib.\n\nMohon kerja samanya untuk menjaga kebersihan mushaf dan mengembalikannya ke tempat semula setelah selesai dibaca. Semoga berkah bagi para pewakaf dan pembacanya.',
    tipe: 'Informasi',
    tautanDonasi: false,
    gambarUrl: 'https://images.unsplash.com/photo-1609599006353-e629f1d00f18?q=80&w=800&auto=format&fit=crop',
    dibuatOleh: 'sekretaris@masjid.org',
    namaPembuat: 'Budi Raharjo',
    timestamp: '2026-07-04T10:30:00Z'
  }
];
